version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
      - DEBUG=false
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
