version: '3.8'
services:
  resume-tailor:
    build: .
    ports:
      - '5000:5000'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    volumes:
      - ./uploads:/app/uploads
